<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<OutputPath>..\Assemblies\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Optimize>true</Optimize>
		<DebugType>portable</DebugType>
		<AssemblyName>MountainTool</AssemblyName>
		<RootNamespace>MountainTool</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4535" />
	</ItemGroup>
</Project>
